insert into public.categories (expense_name) values ('taxes');
insert into public.categories (expense_name) values ('repairs');
insert into public.categories (expense_name) values ('credit');
insert into public.categories (expense_name) values ('rent');
insert into public.categories (expense_name) values ('health');
insert into public.categories (expense_name) values ('housekeeping');
insert into public.categories (expense_name) values ('Internet');
insert into public.categories (expense_name) values ('foodstuffs');
insert into public.categories (expense_name) values ('repairs');
insert into public.categories (income_name) values ('salary');
insert into public.categories (income_name) values ('cashback');
insert into public.categories (income_name) values ('premium/prize');
insert into public.categories (income_name) values ('inheritance');
insert into public.categories (income_name) values ('money transfer');
insert into public.categories (income_name) values ('grants');
insert into public.categories (expense_name) values ('technic');
insert into public.categories (expense_name) values ('entertainment');
insert into public.categories (expense_name) values ('utilities');
insert into public.categories (income_name) values ('dividends');
insert into public.categories (income_name) values ('pension');
insert into public.categories (income_name) values ('social benefit');
insert into public.categories (income_name) values ('deposit interest');
insert into users(email) values ('aligator666@gmail.com');
insert into users(email) values ('sashapetrow@gmail.com');
insert into users(email) values ('miwagorbi@gmail.com');
insert into public.accounts (account_name, balance, user_id) values ('Personal account', '10500', '1');
insert into public.accounts (account_name, balance, user_id) values ('Deposit account', '7500', '1');
insert into public.accounts (account_name, balance, user_id) values ('Checking account', '12200', '2');
insert into public.accounts (account_name, balance, user_id) values ('Loan account', '15000', '3');
insert into public.accounts (account_name, balance, user_id) values ('Personal account', '10000', '3');
insert into public.accounts (account_name, balance, user_id) values ('Deposit account', '50000', '3');
insert into public.operations(passed_at, transaction, account_id) values ('15.04.2020', '45000', '1');
insert into public.operations_categories(operation_id, category_id) values ('1', '21');
insert into public.operations_categories(operation_id, category_id) values ('1', '22');
insert into public.operations(passed_at, transaction, account_id) values ('17.01.2021', '-34500', '1');
insert into public.operations_categories(operation_id, category_id) values ('2', '5');
insert into public.operations_categories(operation_id, category_id) values ('2', '7');
insert into public.operations(passed_at, transaction, account_id) values ('17.01.2021', '10000', '2');
insert into public.operations_categories(operation_id, category_id) values ('3', '21');
insert into public.operations_categories(operation_id, category_id) values ('3', '10');
insert into public.operations(passed_at, transaction, account_id) values ('17.01.2021', '-200', '2');
insert into public.operations_categories(operation_id, category_id) values ('4', '5');
insert into public.operations_categories(operation_id, category_id) values ('4', '7');
insert into public.operations(passed_at, transaction, account_id) values ('17.01.2021', '12400', '3');
insert into public.operations_categories(operation_id, category_id) values ('5', '21');
insert into public.operations_categories(operation_id, category_id) values ('5', '10');
insert into public.operations(passed_at, transaction, account_id) values ('17.01.2021', '-200', '3');
insert into public.operations_categories(operation_id, category_id) values ('6', '5');
insert into public.operations_categories(operation_id, category_id) values ('6', '7');
insert into public.operations(passed_at, transaction, account_id) values ('13.06.2021', '14545', '4');
insert into public.operations_categories(operation_id, category_id) values ('7', '15');
insert into public.operations(passed_at, transaction, account_id) values ('11.06.2021', '455', '4');
insert into public.operations_categories(operation_id, category_id) values ('8', '14');

