insert into public.courses (course_name) values ('java');
insert into public.courses (course_name) values ('python');
insert into public.courses (course_name) values ('js');
insert into public.groups (group_name, course_id) values ('nix-4', '1');
insert into public.groups (group_name, course_id) values ('python-alevel-2', '2');
insert into public.groups (group_name, course_id) values ('2020-js-nix', '3');
insert into public.topics (topic_name) values ('java reflection');
insert into public.topics (topic_name) values ('OOP');
insert into public.topics (topic_name) values ('Strings');
insert into public.topics (topic_name) values ('Python Abstract classes');
insert into public.topics (topic_name) values ('Context Manager');
insert into public.marks (mark) values ('20');
insert into public.marks (mark) values ('21');
insert into public.marks (mark) values ('22');
insert into public.marks (mark) values ('23');
insert into public.marks (mark) values ('19');
insert into public.marks (mark) values ('30');
insert into public.teachers (first_name, last_name) values ('Misha', 'Misha');
insert into public.teachers (first_name, last_name) values ('Iegor', 'Iegor');
insert into public.teachers (first_name, last_name) values ('Pasha', 'Pasha');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Lucy', 'Gorbachova', '1', '6');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Pasha', 'Cyber', '1', '4');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Ivan', 'Ivanov', '1', '6');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Sasha', 'Zinchenko', '2', '1');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Masha', 'Litvin', '2', '2');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Alina', 'Kursha', '2', '3');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Kamal', 'Ahdiev', '3', '5');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Ivan', 'Surkov', '3', '5');
insert into public.students (first_name, last_name, group_id, mark_id) values ('Andey', 'Andreev', '3', '6');
insert into public.lessons (description, date, time,group_id, teacher_id, topic_id ) values ('first lesson', '21.07.2021','15:00:00', '3','3','2');
insert into public.lessons (description, date, time,group_id, teacher_id, topic_id ) values ('first lesson', '15.06.2021','15:00:00','1' ,'1','2');
insert into public.lessons (description, date, time,group_id, teacher_id, topic_id ) values ('first lesson continue', '15.06.2021','18:00:00','1' ,'1','2');
insert into public.lessons (description, date, time,group_id, teacher_id, topic_id ) values (null, '17.06.2021','15:00:00', '1','2','1');
insert into public.lessons (description, date, time,group_id, teacher_id, topic_id ) values ('context manager 1 lesson', '13.08.2021','15:00:00', '2','3','5');